name: curso_arcgis_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  arcgis_maps: ^200.8.0+4672
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.1
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5
  bloc: ^9.0.0

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
