name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarqube:
    name: SonarQube
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 
      - name: Create .env file from secrets
        run: |
          echo "ARCGIS_API_KEY=${{ secrets.ARCGIS_API_KEY }}" > .env
          echo "URL_FEATURE_LAYER_POBLADOS_MARGARITA=${{ secrets.URL_FEATURE_LAYER_POBLADOS_MARGARITA }}" >> .env
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable' # o la versión que necesites, ej: '3.22.0'
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Get Flutter dependencies
        run: flutter pub get
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@master # Using master for latest updates
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - name: Build android application
        run: flutter build apk --release
      - name: Build iOS application
        run: flutter build ios --release --no-codesign